name: zcash_dart
description: >
  zcash_dart is a Dart package that implements Zcash cryptography and transaction
  management, including Sapling, Orchard, and transparent transactions.
  It provides utilities for key management, proofs, and walletd interaction.
version: 0.1.0
homepage: "https://github.com/mrtnetwork/zcash_dart"
repository: "https://github.com/mrtnetwork/zcash_dart"
Author: mrhaydari.t@gmail.com
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.7.0 <4.0.0'
# Add regular dependencies here.
dependencies:
  blockchain_utils: ^6.0.0
  bitcoin_base: ^7.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
