name: zcash_dart
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.7.0 <4.0.0'
# Add regular dependencies here.
dependencies:
  blockchain_utils: ^6.0.0
  bitcoin_base: ^7.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
